import React, {Component} from 'react'
import {StyleSheet, View, Text, ScrollView} from 'react-native'

export default class RecommendPage extends Component {
  render() {
    return (
      <ScrollView>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>255</Text>
        </View>
        <View>
          <Text>2444</Text>
        </View>
        <View>
          <Text>2333</Text>
        </View>
      </ScrollView>
    )
  }
}
