import React, {Component} from 'react'
import {connect} from 'react-redux'
import {StyleSheet, View, Text, ScrollView} from 'react-native'
import ViewPager from 'react-native-viewpager'

class RecommendPage extends Component {
  render() {
    const {bannerList} = this.props
    console.log(bannerList)
    return (
      <ScrollView>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>2</Text>
        </View>
        <View>
          <Text>255</Text>
        </View>
        <View>
          <Text>2444</Text>
        </View>
        <View>
          <Text>2333</Text>
        </View>
      </ScrollView>
    )
  }
}

export default connect((store) => ({
  bannerList: store.recommend.bannerList
}))(RecommendPage)
